//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApi.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string AppLanguage_Eng {
            get {
                return ResourceManager.GetString("AppLanguage_Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string AppLanguage_Rus {
            get {
                return ResourceManager.GetString("AppLanguage_Rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string AppLanguage_Ukr {
            get {
                return ResourceManager.GetString("AppLanguage_Ukr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matter.
        /// </summary>
        public static string CommunicationPreference_NoMatter {
            get {
                return ResourceManager.GetString("CommunicationPreference_NoMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string CommunicationPreference_Offline {
            get {
                return ResourceManager.GetString("CommunicationPreference_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string CommunicationPreference_Online {
            get {
                return ResourceManager.GetString("CommunicationPreference_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have run out of tag searches for today.\nYou can still use Card Deck Mini or Card Deck Premium to replenish your views, buy premium and thus double your view count, or wait until tomorrow :).
        /// </summary>
        public static string Familiator_OutOfTags {
            get {
                return ResourceManager.GetString("Familiator_OutOfTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have run out of profile searches for today.\nYou can still use Card Deck Mini or Card Deck Premium to replenish your views, buy premium and thus double your view count, or wait until tomorrow :).
        /// </summary>
        public static string Familiator_OutOfViews {
            get {
                return ResourceManager.GetString("Familiator_OutOfViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string FeedbackReason_Test {
            get {
                return ResourceManager.GetString("FeedbackReason_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-binary.
        /// </summary>
        public static string Gender_NonBinary {
            get {
                return ResourceManager.GetString("Gender_NonBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matter.
        /// </summary>
        public static string Gender_RatherNotSay {
            get {
                return ResourceManager.GetString("Gender_RatherNotSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        public static string ReportReason_Spam {
            get {
                return ResourceManager.GetString("ReportReason_Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just testing out.
        /// </summary>
        public static string ReportReason_TestReason {
            get {
                return ResourceManager.GetString("ReportReason_TestReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string UsageReason_Communication {
            get {
                return ResourceManager.GetString("UsageReason_Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendship.
        /// </summary>
        public static string UsageReason_Friendship {
            get {
                return ResourceManager.GetString("UsageReason_Friendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matter.
        /// </summary>
        public static string UsageReason_NoMatter {
            get {
                return ResourceManager.GetString("UsageReason_NoMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string UsageReason_Relationship {
            get {
                return ResourceManager.GetString("UsageReason_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just sex.
        /// </summary>
        public static string UsageReason_Sex {
            get {
                return ResourceManager.GetString("UsageReason_Sex", resourceCulture);
            }
        }
    }
}
