//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApi.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string AppLanguage_Eng {
            get {
                return ResourceManager.GetString("AppLanguage_Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string AppLanguage_Rus {
            get {
                return ResourceManager.GetString("AppLanguage_Rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string AppLanguage_Ukr {
            get {
                return ResourceManager.GetString("AppLanguage_Ukr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matter.
        /// </summary>
        public static string CommunicationPreference_NoMatter {
            get {
                return ResourceManager.GetString("CommunicationPreference_NoMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string CommunicationPreference_Offline {
            get {
                return ResourceManager.GetString("CommunicationPreference_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string CommunicationPreference_Online {
            get {
                return ResourceManager.GetString("CommunicationPreference_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZK [Kč].
        /// </summary>
        public static string Currency_CZK {
            get {
                return ResourceManager.GetString("Currency_CZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR [€].
        /// </summary>
        public static string Currency_EUR {
            get {
                return ResourceManager.GetString("Currency_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLN [zł].
        /// </summary>
        public static string Currency_PLN {
            get {
                return ResourceManager.GetString("Currency_PLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUB.
        /// </summary>
        public static string Currency_RUB {
            get {
                return ResourceManager.GetString("Currency_RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAH [₴].
        /// </summary>
        public static string Currency_UAH {
            get {
                return ResourceManager.GetString("Currency_UAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD [$].
        /// </summary>
        public static string Currency_USD {
            get {
                return ResourceManager.GetString("Currency_USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💎 USDT 💎.
        /// </summary>
        public static string Currency_USDC {
            get {
                return ResourceManager.GetString("Currency_USDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Deck Mini.
        /// </summary>
        public static string Effect_CardDeckMini {
            get {
                return ResourceManager.GetString("Effect_CardDeckMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Deck Platinum.
        /// </summary>
        public static string Effect_CardDeckPlatinum {
            get {
                return ResourceManager.GetString("Effect_CardDeckPlatinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullifier.
        /// </summary>
        public static string Effect_Nullifier {
            get {
                return ResourceManager.GetString("Effect_Nullifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Chance.
        /// </summary>
        public static string Effect_SecondChance {
            get {
                return ResourceManager.GetString("Effect_SecondChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Detector.
        /// </summary>
        public static string Effect_TheDetector {
            get {
                return ResourceManager.GetString("Effect_TheDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Valentine.
        /// </summary>
        public static string Effect_TheValentine {
            get {
                return ResourceManager.GetString("Effect_TheValentine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have run out of tag searches for today.\nYou can still use Card Deck Mini or Card Deck Premium to replenish your views, buy premium and thus double your view count, or wait until tomorrow :).
        /// </summary>
        public static string Familiator_OutOfTags {
            get {
                return ResourceManager.GetString("Familiator_OutOfTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have run out of profile searches for today.\nYou can still use Card Deck Mini or Card Deck Premium to replenish your views, buy premium and thus double your view count, or wait until tomorrow :).
        /// </summary>
        public static string Familiator_OutOfViews {
            get {
                return ResourceManager.GetString("Familiator_OutOfViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest &quot;Hints&quot;.
        /// </summary>
        public static string FeedbackReason_SuggestHints {
            get {
                return ResourceManager.GetString("FeedbackReason_SuggestHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Suggestion.
        /// </summary>
        public static string FeedbackReason_Suggestion {
            get {
                return ResourceManager.GetString("FeedbackReason_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-binary.
        /// </summary>
        public static string Gender_NonBinary {
            get {
                return ResourceManager.GetString("Gender_NonBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matter.
        /// </summary>
        public static string Gender_RatherNotSay {
            get {
                return ResourceManager.GetString("Gender_RatherNotSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        public static string ReportReason_Spam {
            get {
                return ResourceManager.GetString("ReportReason_Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just testing out.
        /// </summary>
        public static string ReportReason_TestReason {
            get {
                return ResourceManager.GetString("ReportReason_TestReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string UsageReason_Communication {
            get {
                return ResourceManager.GetString("UsageReason_Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendship.
        /// </summary>
        public static string UsageReason_Friendship {
            get {
                return ResourceManager.GetString("UsageReason_Friendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matter.
        /// </summary>
        public static string UsageReason_NoMatter {
            get {
                return ResourceManager.GetString("UsageReason_NoMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string UsageReason_Relationship {
            get {
                return ResourceManager.GetString("UsageReason_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just sex.
        /// </summary>
        public static string UsageReason_Sex {
            get {
                return ResourceManager.GetString("UsageReason_Sex", resourceCulture);
            }
        }
    }
}
