// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20230603113719_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Entities.AchievementEntities.Achievement", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<int>("ConditionValue")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id", "ClassLocalisationId");

                    b.ToTable("SYSTEM_ACHIEVEMENTS");
                });

            modelBuilder.Entity("WebApi.Entities.AchievementEntities.UserAchievement", b =>
                {
                    b.Property<long>("UserBaseInfoId")
                        .HasColumnType("bigint");

                    b.Property<long>("AchievementId")
                        .HasColumnType("bigint");

                    b.Property<int>("AchievementClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<string>("AcquireMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsAcquired")
                        .HasColumnType("boolean");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("UserBaseInfoId", "AchievementId");

                    b.HasIndex("UserId");

                    b.HasIndex("AchievementId", "AchievementClassLocalisationId");

                    b.ToTable("USER_ACHIEVEMENTS");
                });

            modelBuilder.Entity("WebApi.Entities.AdminEntities.Admin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("SYSTEM_ADMINS");
                });

            modelBuilder.Entity("WebApi.Entities.AdminEntities.TickRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("AdminId")
                        .HasColumnType("bigint");

                    b.Property<string>("Circle")
                        .HasColumnType("text");

                    b.Property<string>("Gesture")
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<int?>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Video")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tick_requests");
                });

            modelBuilder.Entity("WebApi.Entities.AdventureEntities.Adventure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Application")
                        .HasColumnType("text");

                    b.Property<string>("AttendeesDescription")
                        .HasColumnType("text");

                    b.Property<string>("AutoReply")
                        .HasColumnType("text");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .HasColumnType("text");

                    b.Property<string>("Gratitude")
                        .HasColumnType("text");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("GroupLink")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAutoReplyText")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAwaiting")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMediaPhoto")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOffline")
                        .HasColumnType("boolean");

                    b.Property<string>("Media")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Time")
                        .HasColumnType("text");

                    b.Property<string>("UniqueLink")
                        .HasColumnType("text");

                    b.Property<string>("UnwantedAttendeesDescription")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("adventures");
                });

            modelBuilder.Entity("WebApi.Entities.AdventureEntities.AdventureAttendee", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("UserId", "AdventureId");

                    b.HasIndex("AdventureId");

                    b.ToTable("adventure_attendees");
                });

            modelBuilder.Entity("WebApi.Entities.AdventureEntities.AdventureTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Application")
                        .HasColumnType("text");

                    b.Property<string>("AttendeesDescription")
                        .HasColumnType("text");

                    b.Property<string>("AutoReply")
                        .HasColumnType("text");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .HasColumnType("text");

                    b.Property<string>("Gratitude")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAutoReplyText")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMediaPhoto")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOffline")
                        .HasColumnType("boolean");

                    b.Property<string>("Media")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .HasColumnType("text");

                    b.Property<string>("UnwantedAttendeesDescription")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("adventure_templates");
                });

            modelBuilder.Entity("WebApi.Entities.DailyRewardEntities.DailyReward", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Index")
                        .HasColumnType("smallint");

                    b.Property<int>("PointReward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DAILY_REWARDS");
                });

            modelBuilder.Entity("WebApi.Entities.DailyTaskEntities.DailyTask", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Reward")
                        .HasColumnType("integer");

                    b.Property<short>("RewardCurrency")
                        .HasColumnType("smallint");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer");

                    b.Property<short>("TaskType")
                        .HasColumnType("smallint");

                    b.HasKey("Id", "ClassLocalisationId");

                    b.ToTable("DAILY_TASKS");
                });

            modelBuilder.Entity("WebApi.Entities.DailyTaskEntities.UserDailyTask", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("DailyTaskId")
                        .HasColumnType("bigint");

                    b.Property<string>("AcquireMessage")
                        .HasColumnType("text");

                    b.Property<int>("DailyTaskClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAcquired")
                        .HasColumnType("boolean");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "DailyTaskId");

                    b.HasIndex("DailyTaskId", "DailyTaskClassLocalisationId");

                    b.ToTable("USER_DAILY_TASKS");
                });

            modelBuilder.Entity("WebApi.Entities.EffectEntities.ActiveEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EffectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("ExpiresIn")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("USER_ACTIVE_EFFECTS");
                });

            modelBuilder.Entity("WebApi.Entities.HintEntities.Hint", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<int?>("Section")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id", "ClassLocalisationId");

                    b.ToTable("hints");
                });

            modelBuilder.Entity("WebApi.Entities.LocalisationEntities.AppLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageName")
                        .HasColumnType("text");

                    b.Property<string>("LanguageNameShort")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("APP_LANGUAGES");
                });

            modelBuilder.Entity("WebApi.Entities.LocalisationEntities.ClassLocalization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CLASS_LOCALISATIONS");
                });

            modelBuilder.Entity("WebApi.Entities.LocalisationEntities.Localization", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageName")
                        .HasColumnType("text");

                    b.Property<string>("SectionName")
                        .HasColumnType("text");

                    b.HasKey("Id", "SectionId");

                    b.ToTable("LOCALISATIONS");
                });

            modelBuilder.Entity("WebApi.Entities.LocalisationEntities.SecondaryLocalizationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ElementName")
                        .HasColumnType("text");

                    b.Property<string>("ElementText")
                        .HasColumnType("text");

                    b.Property<int>("LocalisationId")
                        .HasColumnType("integer");

                    b.Property<int>("LocalisationSectionId")
                        .HasColumnType("integer");

                    b.Property<int?>("LocalizationId")
                        .HasColumnType("integer");

                    b.Property<int?>("LocalizationSectionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalizationId", "LocalizationSectionId");

                    b.ToTable("SECONDARY_LOCALISATIONS");
                });

            modelBuilder.Entity("WebApi.Entities.LocationEntities.City", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("CountryClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<string>("CityName")
                        .HasColumnType("text");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.HasKey("Id", "CountryClassLocalisationId");

                    b.HasIndex("CountryClassLocalisationId", "CountryId");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("WebApi.Entities.LocationEntities.Country", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<string>("CountryName")
                        .HasColumnType("text");

                    b.Property<short?>("Priority")
                        .HasColumnType("smallint");

                    b.HasKey("Id", "ClassLocalisationId");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("WebApi.Entities.LocationEntities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CityCountryClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<int?>("CountryClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityCountryClassLocalisationId", "CityId");

                    b.HasIndex("CountryClassLocalisationId", "CountryId");

                    b.ToTable("USER_LOCATIONS");
                });

            modelBuilder.Entity("WebApi.Entities.LocationEntities.UpdateCountry", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassLocalizationId")
                        .HasColumnType("integer");

                    b.Property<string>("CountryName")
                        .HasColumnType("text");

                    b.HasKey("Id", "ClassLocalisationId");

                    b.HasIndex("ClassLocalizationId");

                    b.ToTable("UpdateCountry");
                });

            modelBuilder.Entity("WebApi.Entities.ReasonEntities.FeedbackReason", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<int>("ClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id", "ClassLocalisationId");

                    b.ToTable("FEEDBACK_REASONS");
                });

            modelBuilder.Entity("WebApi.Entities.ReportEntities.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("InsertedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReasonClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<short>("ReasonId")
                        .HasColumnType("smallint");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ReasonId", "ReasonClassLocalisationId");

                    b.ToTable("SYSTEM_FEEDBACKS");
                });

            modelBuilder.Entity("WebApi.Entities.ReportEntities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InsertedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Reason")
                        .HasColumnType("smallint");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("USER_REPORTS");
                });

            modelBuilder.Entity("WebApi.Entities.SecondaryEntities.AgePreference", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<short>("ClassLocalisationId")
                        .HasColumnType("smallint");

                    b.Property<string>("AgePrefName")
                        .HasColumnType("text");

                    b.HasKey("Id", "ClassLocalisationId");

                    b.ToTable("AGE_PREFERENCES");
                });

            modelBuilder.Entity("WebApi.Entities.SecondaryEntities.CommunicationPreference", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<int>("ClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<string>("CommunicationPrefName")
                        .HasColumnType("text");

                    b.HasKey("Id", "ClassLocalisationId");

                    b.ToTable("COMMUNICATION_PREFERENCES");
                });

            modelBuilder.Entity("WebApi.Entities.SecondaryEntities.Gender", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<int>("ClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassLocalizationId")
                        .HasColumnType("integer");

                    b.Property<string>("GenderName")
                        .HasColumnType("text");

                    b.HasKey("Id", "ClassLocalisationId");

                    b.HasIndex("ClassLocalizationId");

                    b.ToTable("SYSTEM_GENDERS");
                });

            modelBuilder.Entity("WebApi.Entities.SecondaryEntities.Language", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassLocalizationId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageName")
                        .HasColumnType("text");

                    b.Property<string>("LanguageNameNative")
                        .HasColumnType("text");

                    b.Property<short?>("Priority")
                        .HasColumnType("smallint");

                    b.HasKey("Id", "ClassLocalisationId");

                    b.HasIndex("ClassLocalizationId");

                    b.ToTable("LANGUAGES");
                });

            modelBuilder.Entity("WebApi.Entities.SecondaryEntities.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardDeckMini")
                        .HasColumnType("integer");

                    b.Property<int>("CardDeckPlatinum")
                        .HasColumnType("integer");

                    b.Property<int>("Nullifier")
                        .HasColumnType("integer");

                    b.Property<int>("PersonalityPoints")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Promo")
                        .HasColumnType("text");

                    b.Property<int>("SecondChance")
                        .HasColumnType("integer");

                    b.Property<int>("TheDetector")
                        .HasColumnType("integer");

                    b.Property<int>("TheValentine")
                        .HasColumnType("integer");

                    b.Property<bool>("UsedOnlyInRegistration")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("promo_codes");
                });

            modelBuilder.Entity("WebApi.Entities.SecondaryEntities.UserReason", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<int>("ClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonName")
                        .HasColumnType("text");

                    b.HasKey("Id", "ClassLocalisationId");

                    b.ToTable("USER_REASONS");
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.Ad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<long>("SponsorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Video")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.ToTable("SPONSOR_ADS");
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Bounty")
                        .HasColumnType("integer");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GroupLink")
                        .HasColumnType("text");

                    b.Property<bool>("HasGroup")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<List<int?>>("Languages")
                        .HasColumnType("integer[]");

                    b.Property<short>("MaxAge")
                        .HasColumnType("smallint");

                    b.Property<short>("MinAge")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<long>("SponsorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.ToTable("SPONSOR_EVENTS");
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.EventTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Bounty")
                        .HasColumnType("integer");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<List<int?>>("Languages")
                        .HasColumnType("integer[]");

                    b.Property<short>("MaxAge")
                        .HasColumnType("smallint");

                    b.Property<short>("MinAge")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<long>("SponsorId")
                        .HasColumnType("bigint");

                    b.Property<string>("TemplateName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SPONSOR_EVENT_TEMPLATES");
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.Sponsor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("CodeWord")
                        .HasColumnType("text");

                    b.Property<long?>("ContactInfoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasBaseAccount")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAwaiting")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPostponed")
                        .HasColumnType("boolean");

                    b.Property<long?>("StatsId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserAppLanguage")
                        .HasColumnType("integer");

                    b.Property<int>("UserCityId")
                        .HasColumnType("integer");

                    b.Property<int>("UserCountryId")
                        .HasColumnType("integer");

                    b.Property<int>("UserMaxAdCount")
                        .HasColumnType("integer");

                    b.Property<int>("UserMaxAdViewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactInfoId");

                    b.HasIndex("StatsId");

                    b.ToTable("SYSTEM_SPONSORS");
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.SponsorContactInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Facebook")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("SponsorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("SPONSOR_CONTACT_INFO");
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.SponsorLanguage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("LanguageClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<short>("Level")
                        .HasColumnType("smallint");

                    b.Property<long>("SponsorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.HasIndex("LanguageClassLocalisationId", "LanguageId");

                    b.ToTable("SPONSOR_LANGUAGES");
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.SponsorNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<short>("NotificationReason")
                        .HasColumnType("smallint");

                    b.Property<long>("SponsorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.ToTable("SPONSOR_NOTIFICATIONS");
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.SponsorRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CommentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint");

                    b.Property<long>("SponsorId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.HasIndex("UserId");

                    b.ToTable("SPONSOR_RATINGS");
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.Stats", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<int>("ConductedEventsCount")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<double>("LevelGoal")
                        .HasColumnType("double precision");

                    b.Property<double>("LevelProgress")
                        .HasColumnType("double precision");

                    b.Property<long>("SponsorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SPONSOR_STATS");
                });

            modelBuilder.Entity("WebApi.Entities.TestEntities.Test", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<int>("CanBePassedInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<short>("TestType")
                        .HasColumnType("smallint");

                    b.HasKey("Id", "ClassLocalisationId");

                    b.ToTable("tests");
                });

            modelBuilder.Entity("WebApi.Entities.TestEntities.TestAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<long>("TestQuestionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TestQuestionId");

                    b.ToTable("tests_answers");
                });

            modelBuilder.Entity("WebApi.Entities.TestEntities.TestQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<int>("TestClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TestId", "TestClassLocalisationId");

                    b.ToTable("tests_questions");
                });

            modelBuilder.Entity("WebApi.Entities.TestEntities.TestResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<int>("TestClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestId", "TestClassLocalisationId");

                    b.ToTable("tests_results");
                });

            modelBuilder.Entity("WebApi.Entities.UserActionEntities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InvitationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("InvitedUserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("InvitorCredentialsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvitorCredentialsId");

                    b.ToTable("USER_INVITATIONS");
                });

            modelBuilder.Entity("WebApi.Entities.UserActionEntities.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsLikedBack")
                        .HasColumnType("boolean");

                    b.Property<int>("Section")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("USER_NOTIFICATIONS");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.Balance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardDecksMini")
                        .HasColumnType("integer");

                    b.Property<int>("CardDecksPlatinum")
                        .HasColumnType("integer");

                    b.Property<int>("Detectors")
                        .HasColumnType("integer");

                    b.Property<int>("Nullifiers")
                        .HasColumnType("integer");

                    b.Property<int>("PersonalityPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PointInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("SecondChances")
                        .HasColumnType("integer");

                    b.Property<int>("ThePersonalities")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Valentines")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("USER_WALLET_BALANCES");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.BlackList", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("BannedUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("BannedUserId");

                    b.ToTable("USER_BLACKLISTS");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EncounterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EncounteredUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EncounteredUserId");

                    b.ToTable("USER_ENCOUNTERS");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.InvitationCredentials", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("QRCode")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("USER_INVITATION_CREDENTIALS");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<short>("Currency")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("PointInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("USER_WALLET_PURCHASES");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BanDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("BonusIndex")
                        .HasColumnType("double precision");

                    b.Property<short?>("Currency")
                        .HasColumnType("smallint");

                    b.Property<short>("DailyRewardPoint")
                        .HasColumnType("smallint");

                    b.Property<long>("DataId")
                        .HasColumnType("bigint");

                    b.Property<string>("EnteredPromoCodes")
                        .HasColumnType("text");

                    b.Property<bool>("HadReceivedReward")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPremium")
                        .HasColumnType("boolean");

                    b.Property<int>("IdentityType")
                        .HasColumnType("integer");

                    b.Property<double>("InvitedUsersBonus")
                        .HasColumnType("double precision");

                    b.Property<int>("InvitedUsersCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBusy")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDecoy")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUpdated")
                        .HasColumnType("boolean");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxProfileViewsCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRTViewsCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTagSearchCount")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<short?>("PremiumDuration")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("PremiumExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProfileViewsCount")
                        .HasColumnType("integer");

                    b.Property<int>("RTViewsCount")
                        .HasColumnType("integer");

                    b.Property<short>("ReportCount")
                        .HasColumnType("smallint");

                    b.Property<long>("SettingsId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ShouldEnhance")
                        .HasColumnType("boolean");

                    b.Property<int>("TagSearchesCount")
                        .HasColumnType("integer");

                    b.Property<long?>("UserSettingsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DataId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserSettingsId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.UserData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<List<int>>("AgePrefs")
                        .HasColumnType("integer[]");

                    b.Property<string>("AutoReplyText")
                        .HasColumnType("text");

                    b.Property<string>("AutoReplyVoice")
                        .HasColumnType("text");

                    b.Property<int>("CommunicationPrefs")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMediaPhoto")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<List<int>>("LanguagePreferences")
                        .HasColumnType("integer[]");

                    b.Property<List<int>>("LocationPreferences")
                        .HasColumnType("integer[]");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<int>("UserAge")
                        .HasColumnType("integer");

                    b.Property<string>("UserDescription")
                        .HasColumnType("text");

                    b.Property<short>("UserGender")
                        .HasColumnType("smallint");

                    b.Property<short>("UserGenderPrefs")
                        .HasColumnType("smallint");

                    b.Property<List<int>>("UserLanguages")
                        .HasColumnType("integer[]");

                    b.Property<string>("UserMedia")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("UserRawDescription")
                        .HasColumnType("text");

                    b.Property<string>("UserRealName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users_data");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.UserEvent", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("USER_EVENTS");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.UserPersonalityPoints", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<int>("Agreeableness")
                        .HasColumnType("integer");

                    b.Property<double>("AgreeablenessPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("Compassion")
                        .HasColumnType("integer");

                    b.Property<double>("CompassionPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("Creativity")
                        .HasColumnType("integer");

                    b.Property<double>("CreativityPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("EmotionalIntellect")
                        .HasColumnType("integer");

                    b.Property<double>("EmotionalIntellectPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("Intellect")
                        .HasColumnType("integer");

                    b.Property<double>("IntellectPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("LevelOfSense")
                        .HasColumnType("integer");

                    b.Property<double>("LevelOfSensePercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("Nature")
                        .HasColumnType("integer");

                    b.Property<double>("NaturePercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("OpenMindedness")
                        .HasColumnType("integer");

                    b.Property<double>("OpenMindednessPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("Personality")
                        .HasColumnType("integer");

                    b.Property<double>("PersonalityPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("Reliability")
                        .HasColumnType("integer");

                    b.Property<double>("ReliabilityPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("SelfAwareness")
                        .HasColumnType("integer");

                    b.Property<double>("SelfAwarenessPercentage")
                        .HasColumnType("double precision");

                    b.HasKey("UserId");

                    b.ToTable("USER_PERSONALITY_POINTS");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.UserPersonalityStats", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<int>("Agreeableness")
                        .HasColumnType("integer");

                    b.Property<int>("Compassion")
                        .HasColumnType("integer");

                    b.Property<int>("Creativity")
                        .HasColumnType("integer");

                    b.Property<int>("EmotionalIntellect")
                        .HasColumnType("integer");

                    b.Property<int>("Intellect")
                        .HasColumnType("integer");

                    b.Property<int>("LevelOfSense")
                        .HasColumnType("integer");

                    b.Property<int>("Nature")
                        .HasColumnType("integer");

                    b.Property<int>("OpenMindedness")
                        .HasColumnType("integer");

                    b.Property<int>("Personality")
                        .HasColumnType("integer");

                    b.Property<int>("Reliability")
                        .HasColumnType("integer");

                    b.Property<int>("SelfAwareness")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("USER_PERSONALITY_STATS");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.UserSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IncreasedFamiliarity")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsFree")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShouldComment")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShouldConsiderLanguages")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShouldFilterUsersWithoutRealPhoto")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShouldSendHints")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShouldUsePersonalityFunc")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("users_settings");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.UserTag", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.Property<int>("TagType")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Tag");

                    b.ToTable("user_tags");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.UserTest", b =>
                {
                    b.Property<long>("TestId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PassedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Result")
                        .HasColumnType("double precision");

                    b.Property<List<string>>("Tags")
                        .HasColumnType("text[]");

                    b.Property<int>("TestClassLocalisationId")
                        .HasColumnType("integer");

                    b.Property<short>("TestType")
                        .HasColumnType("smallint");

                    b.HasKey("TestId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("TestId", "TestClassLocalisationId");

                    b.ToTable("user_tests");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.UserTrustLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Goal")
                        .HasColumnType("double precision");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<double>("Progress")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("USER_TRUST_LEVELS");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.Visit", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "SectionId");

                    b.ToTable("USER_VISITS");
                });

            modelBuilder.Entity("WebApi.Entities.AchievementEntities.UserAchievement", b =>
                {
                    b.HasOne("WebApi.Entities.UserInfoEntities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("WebApi.Entities.AchievementEntities.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId", "AchievementClassLocalisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Entities.AdminEntities.TickRequest", b =>
                {
                    b.HasOne("WebApi.Entities.UserInfoEntities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Entities.AdventureEntities.Adventure", b =>
                {
                    b.HasOne("WebApi.Entities.UserInfoEntities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("WebApi.Entities.AdventureEntities.AdventureAttendee", b =>
                {
                    b.HasOne("WebApi.Entities.AdventureEntities.Adventure", "Adventure")
                        .WithMany()
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adventure");
                });

            modelBuilder.Entity("WebApi.Entities.DailyTaskEntities.UserDailyTask", b =>
                {
                    b.HasOne("WebApi.Entities.DailyTaskEntities.DailyTask", "DailyTask")
                        .WithMany()
                        .HasForeignKey("DailyTaskId", "DailyTaskClassLocalisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyTask");
                });

            modelBuilder.Entity("WebApi.Entities.LocalisationEntities.SecondaryLocalizationModel", b =>
                {
                    b.HasOne("WebApi.Entities.LocalisationEntities.Localization", null)
                        .WithMany("Loc")
                        .HasForeignKey("LocalizationId", "LocalizationSectionId");
                });

            modelBuilder.Entity("WebApi.Entities.LocationEntities.City", b =>
                {
                    b.HasOne("WebApi.Entities.LocationEntities.Country", null)
                        .WithMany("Cities")
                        .HasForeignKey("CountryClassLocalisationId", "CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Entities.LocationEntities.Location", b =>
                {
                    b.HasOne("WebApi.Entities.LocationEntities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityCountryClassLocalisationId", "CityId");

                    b.HasOne("WebApi.Entities.LocationEntities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryClassLocalisationId", "CountryId");

                    b.Navigation("City");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WebApi.Entities.LocationEntities.UpdateCountry", b =>
                {
                    b.HasOne("WebApi.Entities.LocalisationEntities.ClassLocalization", null)
                        .WithMany("Countries")
                        .HasForeignKey("ClassLocalizationId");
                });

            modelBuilder.Entity("WebApi.Entities.ReportEntities.Feedback", b =>
                {
                    b.HasOne("WebApi.Entities.UserInfoEntities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.ReasonEntities.FeedbackReason", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId", "ReasonClassLocalisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reason");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Entities.ReportEntities.Report", b =>
                {
                    b.HasOne("WebApi.Entities.UserInfoEntities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.UserInfoEntities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Entities.SecondaryEntities.Gender", b =>
                {
                    b.HasOne("WebApi.Entities.LocalisationEntities.ClassLocalization", null)
                        .WithMany("Genders")
                        .HasForeignKey("ClassLocalizationId");
                });

            modelBuilder.Entity("WebApi.Entities.SecondaryEntities.Language", b =>
                {
                    b.HasOne("WebApi.Entities.LocalisationEntities.ClassLocalization", null)
                        .WithMany("Languages")
                        .HasForeignKey("ClassLocalizationId");
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.Ad", b =>
                {
                    b.HasOne("WebApi.Entities.SponsorEntities.Sponsor", null)
                        .WithMany("SponsorAds")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.Event", b =>
                {
                    b.HasOne("WebApi.Entities.SponsorEntities.Sponsor", null)
                        .WithMany("SponsorEvents")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.Sponsor", b =>
                {
                    b.HasOne("WebApi.Entities.SponsorEntities.SponsorContactInfo", "SponsorContactInfo")
                        .WithMany()
                        .HasForeignKey("ContactInfoId");

                    b.HasOne("WebApi.Entities.SponsorEntities.Stats", "Stats")
                        .WithMany()
                        .HasForeignKey("StatsId");

                    b.Navigation("SponsorContactInfo");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.SponsorLanguage", b =>
                {
                    b.HasOne("WebApi.Entities.SponsorEntities.Sponsor", null)
                        .WithMany("SponsorLanguages")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.SecondaryEntities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageClassLocalisationId", "LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.SponsorNotification", b =>
                {
                    b.HasOne("WebApi.Entities.SponsorEntities.Sponsor", "Reciever")
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reciever");
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.SponsorRating", b =>
                {
                    b.HasOne("WebApi.Entities.SponsorEntities.Sponsor", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.UserInfoEntities.User", "Commentator")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commentator");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("WebApi.Entities.TestEntities.TestAnswer", b =>
                {
                    b.HasOne("WebApi.Entities.TestEntities.TestQuestion", null)
                        .WithMany("Answers")
                        .HasForeignKey("TestQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Entities.TestEntities.TestQuestion", b =>
                {
                    b.HasOne("WebApi.Entities.TestEntities.Test", null)
                        .WithMany("Questions")
                        .HasForeignKey("TestId", "TestClassLocalisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Entities.TestEntities.TestResult", b =>
                {
                    b.HasOne("WebApi.Entities.TestEntities.Test", null)
                        .WithMany("Results")
                        .HasForeignKey("TestId", "TestClassLocalisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Entities.UserActionEntities.Invitation", b =>
                {
                    b.HasOne("WebApi.Entities.UserInfoEntities.InvitationCredentials", "InvitorCredentials")
                        .WithMany()
                        .HasForeignKey("InvitorCredentialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitorCredentials");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.BlackList", b =>
                {
                    b.HasOne("WebApi.Entities.UserInfoEntities.User", "BannedUser")
                        .WithMany("UserBlackList")
                        .HasForeignKey("BannedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BannedUser");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.Encounter", b =>
                {
                    b.HasOne("WebApi.Entities.UserInfoEntities.User", "EncounteredUser")
                        .WithMany()
                        .HasForeignKey("EncounteredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncounteredUser");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.InvitationCredentials", b =>
                {
                    b.HasOne("WebApi.Entities.UserInfoEntities.User", "Invitor")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitor");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.User", b =>
                {
                    b.HasOne("WebApi.Entities.UserInfoEntities.UserData", "Data")
                        .WithMany()
                        .HasForeignKey("DataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.LocationEntities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.UserInfoEntities.UserSettings", "UserSettings")
                        .WithMany()
                        .HasForeignKey("UserSettingsId");

                    b.Navigation("Data");

                    b.Navigation("Location");

                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.UserEvent", b =>
                {
                    b.HasOne("WebApi.Entities.SponsorEntities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.UserInfoEntities.User", "Attendee")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.UserTag", b =>
                {
                    b.HasOne("WebApi.Entities.UserInfoEntities.User", null)
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.UserTest", b =>
                {
                    b.HasOne("WebApi.Entities.UserInfoEntities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.TestEntities.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId", "TestClassLocalisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Entities.LocalisationEntities.ClassLocalization", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("Genders");

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("WebApi.Entities.LocalisationEntities.Localization", b =>
                {
                    b.Navigation("Loc");
                });

            modelBuilder.Entity("WebApi.Entities.LocationEntities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("WebApi.Entities.SponsorEntities.Sponsor", b =>
                {
                    b.Navigation("SponsorAds");

                    b.Navigation("SponsorEvents");

                    b.Navigation("SponsorLanguages");
                });

            modelBuilder.Entity("WebApi.Entities.TestEntities.Test", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("WebApi.Entities.TestEntities.TestQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("WebApi.Entities.UserInfoEntities.User", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("UserBlackList");
                });
#pragma warning restore 612, 618
        }
    }
}
